# Game Constants
WIDTH = 800
HEIGHT = 600
NEG_WIDTH = -800
NEG_HEGIHT = -600
SNAKE_HEAD_WIDTH = 20
HALF_WIDTH = WIDTH // 2
HALF_HEIGHT = HEIGHT // 2
HALF_NEG_WIDTH = NEG_WIDTH // 2
HALF_NEG_HEIGHT = NEG_HEGIHT // 2
BALL_DIAMETER = 20
SCREEN_SIZE = (WIDTH, HEIGHT)
POS_SCREEN_SIZE = (HALF_WIDTH, HALF_HEIGHT)
NEG_SCREEN_SIZE = (HALF_NEG_WIDTH, HALF_NEG_HEIGHT)